데이터 타입

In [2]:
import torch

ft = torch.FloatTensor([1,2,3])
print(ft)

print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [4]:
#typecasting
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [5]:
it = torch.IntTensor([1,2,3])

print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [6]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)
