In [1]:
import torch

## 텐서의 조작(manipulations)

In [6]:
x = torch.Tensor([[1,2],
                  [3,4]])


print(x)
print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])


print(x[:,1])
print(x[:,0])

print(x[1,:])
print(x[0,:])

print(x[0][1])


tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([2., 4.])
tensor([1., 3.])
tensor([3., 4.])
tensor([1., 2.])
tensor(2.)


view : 텐서의 크기(size)나 모양(shape)을 변경
- 기본적으로 변경 전과 후에 텐서 안의 원소 개수가 유지되어야 함
- -1로 설정되면 계산을 통해 해당 크기값을 유추

In [9]:
x = torch.randn(4,5)
print(x)

y = x.view(20)
print(y)

z = x.view(4,5)
print(z) 

tensor([[ 1.3887, -1.6392, -0.6708,  0.3801,  0.8243],
        [-0.3623,  0.6363, -0.0326,  0.0766, -1.0314],
        [-0.0656,  0.7681,  0.5157,  0.5263,  1.1322],
        [ 1.5296, -1.1300,  1.8142, -1.2419,  2.8053]])
tensor([ 1.3887, -1.6392, -0.6708,  0.3801,  0.8243, -0.3623,  0.6363, -0.0326,
         0.0766, -1.0314, -0.0656,  0.7681,  0.5157,  0.5263,  1.1322,  1.5296,
        -1.1300,  1.8142, -1.2419,  2.8053])
tensor([[ 1.3887, -1.6392, -0.6708,  0.3801,  0.8243],
        [-0.3623,  0.6363, -0.0326,  0.0766, -1.0314],
        [-0.0656,  0.7681,  0.5157,  0.5263,  1.1322],
        [ 1.5296, -1.1300,  1.8142, -1.2419,  2.8053]])
