## 텐서의 연산(Operations)
- 텐서의 대한 수학 연산, 삼각함수, 비트 연산, 비교 연산, 집계 등 제공

In [15]:
import math
import torch

a = torch.rand(1,2) * 2 -1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5,0.5))

print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,2,])))


tensor([[0.7423, 0.0062]])
tensor([[0.7423, 0.0062]])
tensor([[1., 1.]])
tensor([[0., 0.]])
tensor([[0.5000, 0.0062]])
tensor([[0.7423, 0.0062]])
tensor(0.0062)
tensor(0.7423)
tensor(0.3743)
tensor(0.5205)
tensor(0.0046)
tensor([1, 2, 3])


max와 min은 dim 인자를 줄 경우 argmax와 argmin도 함께 리턴
- argmax : 최대값을 가진 인덱스
- argmin : 최소값을 가진 인덱스

In [17]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.2315, 0.8535],
        [0.8517, 0.0766]])
torch.return_types.max(
values=tensor([0.8517, 0.8535]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([0.8535, 0.8517]),
indices=tensor([1, 0]))


In [18]:
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.2315, 0.8535],
        [0.8517, 0.0766]])
torch.return_types.min(
values=tensor([0.2315, 0.0766]),
indices=tensor([0, 1]))
torch.return_types.min(
values=tensor([0.2315, 0.0766]),
indices=tensor([0, 1]))


In [19]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.5625, 0.6794],
        [0.5650, 0.9051]])
tensor([[0.5370, 0.0045],
        [0.7313, 0.4383]])


In [20]:
# torch.add -> 덧셈
print(x + y)
print(torch.add(x,y))

#두 개의 결과값은 동일

tensor([[1.0995, 0.6839],
        [1.2962, 1.3433]])
tensor([[1.0995, 0.6839],
        [1.2962, 1.3433]])


결과 텐서를 인자로 제공


In [22]:
result = torch.empty(2,4)
torch.add(x,y,out=result)
print(result)

tensor([[1.0995, 0.6839],
        [1.2962, 1.3433]])


/var/folders/vv/gytv0rd10j5_y7gs0ms_23500000gn/T/ipykernel_43682/7703770.py:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/Resize.cpp:35.)
  torch.add(x,y,out=result)


##### in-place 방식
- in-place 방식으로 텐서의 값을 변경하는 연산 뒤에는 _"가 붙음
- x.copy_(y), x.t_()

In [25]:
print(x)
print(y)

y.add_(x)

print(y)




tensor([[0.5625, 0.6794],
        [0.5650, 0.9051]])
tensor([[1.6620, 1.3633],
        [1.8612, 2.2484]])
tensor([[2.2245, 2.0426],
        [2.4262, 3.1534]])


In [33]:
# 뺄셈

print(torch.sub(x,y))

#나눗셈

print(torch.div(x,y))

# 곱셈

print(torch.mul(x,y))

#내적
print(torch.matmul(x,y))

#토치 행렬분해
z = torch.mm(x,y)
print(torch.svd(z))

tensor([[-1.6620, -1.3633],
        [-1.8612, -2.2484]])
tensor([[0.2529, 0.3326],
        [0.2329, 0.2870]])
tensor([[1.2513, 1.3877],
        [1.3708, 2.8540]])
tensor([[2.8996, 3.2913],
        [3.4527, 4.0081]])
torch.return_types.svd(
U=tensor([[-0.6383, -0.7698],
        [-0.7698,  0.6383]]),
S=tensor([6.8720, 0.0375]),
V=tensor([[-0.6561, -0.7547],
        [-0.7547,  0.6561]]))
