텐서 초기화와 데이터 타입

In [6]:
# 초기화 되지않은 텐서
import torch

x = torch.empty(4,2)
y = torch.empty(4,2)
print(y)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [8]:
# 무작위
x = torch.rand(4,2)
print(x)

tensor([[0.4654, 0.7644],
        [0.5187, 0.0618],
        [0.3957, 0.8585],
        [0.4010, 0.3334]])


In [10]:
# 데이터 타입(dtype)이 Long이고, 0으로 채워진 텐서
x = torch.zeros(4,2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [14]:
#사용자가 입력한 값으로 텐서 초기화

x = torch.tensor([3,2.3])

print(x)

x = torch.ones(2,4)
print(x)

# x와 같은 크기, float 타입, 무작위로 채워진 텐서
x = torch.randn_like(x,dtype=torch.float32)
print(x)

tensor([3.0000, 2.3000])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[ 0.4786, -2.1607, -0.2683, -1.3029],
        [-0.8486,  1.6719, -0.5788, -1.2189]])


In [15]:
# 텐서의 크기 계산
print(x.size())

torch.Size([2, 4])
