### Section 2. N차원 배열 인덱싱

In [1]:
import numpy as np

#### 2-1. 배열의 index 접근하기

In [2]:
# 1차원 배열
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr = np.arange(10)
print(arr)

print(arr[3])

[0 1 2 3 4 5 6 7 8 9]
3


In [6]:
# 2차원 배열
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr,arr.shape, arr.ndim)

print(arr[0][0])
print(arr[0,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2
1
4


In [10]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[3:8])
print(arr[3:])
print(arr[:7])
print(arr[:-1])

[3 4 5 6 7]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8]


In [13]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print(arr[0,:])
print(arr[:,1])

[1 2 3 4]
[ 2  6 10]


In [15]:
print(arr[:3, :])
print(arr[:2, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]


#### 배열의 2-2 Fancy 인덱싱

In [16]:
# 1차원 배열
arr = np.array([5,10,15,20,25,30])
print(arr[[0,2,4]])

[ 5 15 25]


In [18]:
# 2차원 배열
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr[[0,2],2:])
print(arr[1:,[2,3]])

[[ 3  4]
 [11 12]]
[[ 7  8]
 [11 12]]


#### 배열의 2-3 Boolean 인덱싱

In [22]:
arr = np.array([1,2,3,4])
print(arr[[True, False, True, True]])

arr = np.array([[1,2,3,4],
               [5,6,7,8]])

print(arr[[True, False], True])

[1 3 4]
[[1 2 3 4]]


In [23]:
arr = np.array([[1,2,3,4],
               [5,6,7,8]])

print(arr[arr > 4])

[5 6 7 8]
