In [1]:
import numpy as np

### Section 4. N차원 배열 형태 변경

#### 5-1. 배열의 형태 변경 1: reshape()

In [8]:
arr = np.arange(12)
print(arr, arr.ndim)

arr = arr.reshape((3,4))

print(arr,arr.ndim)

# 3차원 배열
arr = arr.reshape((2,3,2))
print(arr,arr.ndim)

# 4차원 배열

arr = arr.reshape((2,2,1,3))
print(arr,arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3
[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4


-  curse of dimensionality : 차원의 저주
1. 데이터 학습을 위해 차원이 증가하면서 학습데이터 수가 차원의 수보다 적어져 성능이 저하되는 현상.
2. 차원이 증가할 수록 개별 차원 내 학습할 데이터 수가 적어지는 현상 발생

** 간단히 말해서, 차원이 증가함에 따라 모델의 성능이 안좋아지는 형상 **

- 차원의 저주 문제에 치명적인 알고리즘이 KNN임

#### 5-2. 배열의 형태 변경 2: resize(), ravel()

In [10]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
arr.resize(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
arr = arr.ravel()  # 1차원 배열로 변경
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
arr = np.arange(1,13)
print(arr)

arr = arr.reshape(3,-1)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
arr = arr.reshape(3,2,-1)
print(arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


#### 5-3. 배열의 형태 변경 3 : expand_dims(),squeeze()

In [22]:
# expand_dims()

arr = np.array([1,2])
print(arr, arr.shape)

arr = np.expand_dims(arr,axis=0)
print(arr,arr.shape)


arr = np.expand_dims(arr,axis=1)
print(arr,arr.shape)

[1 2] (2,)
[[1 2]] (1, 2)
[[[1 2]]] (1, 1, 2)


In [26]:
# squeeze()
# 차원 축소 함수
arr = np.array([[1,2]])

print(arr,arr.shape, arr.ndim)
arr = np.squeeze(arr, axis=0)
print(arr,arr.shape,arr.ndim)


arr = np.array([[[1],
                [2],
                [3]]])

print(arr,arr.shape,arr.ndim)
arr = np.squeeze(arr,axis=0)
print(arr,arr.shape,arr.ndim)

[[1 2]] (1, 2) 2
[1 2] (2,) 1
[[[1]
  [2]
  [3]]] (1, 3, 1) 3
[[1]
 [2]
 [3]] (3, 1) 2


In [27]:
arr = np.array([[[1,2,3]]])

print(arr,arr.shape,arr.ndim)

arr = np.squeeze(arr,axis=1)
print(arr,arr.shape,arr.ndim)

[[[1 2 3]]] (1, 1, 3) 3
[[1 2 3]] (1, 3) 2


#### 5-4. 전치행렬(Transpose)

In [29]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr, arr.shape,arr.ndim)

arr = arr.T
print(arr,arr.shape,arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 2
[[1 4 7]
 [2 5 8]
 [3 6 9]] (3, 3) 2


In [31]:
arr = np.array([[1,2],
                [3,4],
                [5,6]])

arr2 = np.full((3,2),2)

print(arr.dot(arr2))

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

위와 같이 오류가 발생하는이유는 두 행렬을 곱하려면 (m × n) * (n × p) 형태여야 된다.

In [32]:
# 따라서 전치행렬 사용

print((arr).dot(arr2.T))

[[ 6  6  6]
 [14 14 14]
 [22 22 22]]
