In [1]:
import numpy as np

### Section 4. N차원 배열 정렬

#### 4-1. 1차원 배열의 정렬

In [2]:
arr = np.random.randint(10,size=10)
print(arr)

[6 8 2 5 8 1 1 2 1 5]


In [7]:
# 오름차순
print(np.sort(arr))

# 내림차순

print(np.sort(arr)[::-1])

[1 1 1 2 2 5 5 6 8 8]
[8 8 6 5 5 2 2 1 1 1]


In [9]:
print(arr) # 원본 배열에는 해당이 안됌

# 정렬을 유지하려면
arr = np.sort(arr)
print(arr)
arr.sort()
print(arr)

[6 8 2 5 8 1 1 2 1 5]
[1 1 1 2 2 5 5 6 8 8]
[1 1 1 2 2 5 5 6 8 8]


#### 4-2. 2차원 배열의 정렬

In [12]:
arr = np.random.randint(15, size=(3,4))

In [18]:
print(np.sort(arr, axis=0))
print(np.sort(arr, axis=None))

[[ 1  0 10  1]
 [ 2  9 10 10]
 [13 11 14 12]]
[ 0  1  1  2  9 10 10 10 11 12 13 14]


In [19]:
# argsort()
print(np.sort(arr, axis=1))
print(np.argsort(arr,axis=1))

[[10 11 13 14]
 [ 0  1  2 10]
 [ 1  9 10 12]]
[[3 1 0 2]
 [1 3 0 2]
 [0 1 2 3]]


-  이해 힘들어서 https://sofee.tistory.com/13 블로그 참고
1. argsort() -> 정렬 후 인덱스 반환