In [1]:
import numpy as np

### Section 3. N차원 배열 연산법

#### 3-1. 배열의 연산1 : 사칙연산/제곱/제곱근/몫/나머지

In [2]:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr2 = np.array([[2,2,2],
                 [2,2,2],
                 [2,2,2]])

print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [5]:
#덧셈

print(arr1 + arr2)
print(np.add(arr1,arr2))



[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
# 뺄셈
print(arr1 - arr2)
print(np.subtract(arr1,arr2))

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [10]:
# 곱셈
print(arr1 * arr2)

print(np.multiply(arr1,arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [11]:
# 나눗셈
print(arr1 / arr2)
print(np.divide(arr1,arr2))

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [14]:
# 제곱
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr2 = np.array([[2,2,2],
                 [2,2,2],
                 [2,2,2]])

print(arr1 ** 2)
print(np.square(arr1))

# 제곱근
print(np.sqrt(arr1))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [15]:
# 몫
print(arr1 // 2)

# 나머지

print(arr1 % 2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]


#### 3-2. 배열의 연산2 : 내적(dot product)/절댓값/올림/내림/반올림/버림

In [17]:
# 내적

# 1차원 행렬
arr1 = np.array([2,3,4])
arr2 = np.array([1,2,3])

print(np.dot(arr1,arr2))

20


In [19]:
# 2차원 행렬
arr1 = np.array([[1,2],
                [4,5]])

arr2 = np.array([[1,2],
                [0,3]])

print(np.dot(arr1,arr2))

[[ 1  8]
 [ 4 23]]


In [21]:
# 절댓값

arr1 = np.array([[1,2],[3,4]])

print(np.abs(arr1))


[[1 2]
 [3 4]]


In [25]:
# 올림

arr1 = np.array([[1.932, -2.339],
                 [-4.145, 5.206]])

print(np.ceil(arr1))


# 내림
print(np.floor(arr1))

# 반올림
print(np.round(arr1))

# 버림

print(np.trunc(arr1))

[[ 2. -2.]
 [-4.  6.]]
[[ 1. -3.]
 [-5.  5.]]
[[ 2. -2.]
 [-4.  5.]]
[[ 1. -2.]
 [-4.  5.]]


#### 3-3. 배열의 연산3 : min/max/sum/mean/std/cumsum/median

In [26]:
arr = np.array([[1,2,3],[0,1,4]])

In [30]:
# min()
print(np.min(arr))

print(arr.min(axis=1))

0
[1 0]


In [33]:
# max()

print(np.max(arr))
print(arr.max(axis=0))
print(arr.max(axis=1))

4
[1 2 4]
[3 4]


In [35]:
# sum()

print(np.sum(arr))
print(arr.sum(axis=0))
print(arr.sum(axis=1))

11
[1 3 7]
[6 5]


In [38]:
# mean()
print(np.mean(arr))
print(arr.mean(axis=1))

1.8333333333333333
[2.         1.66666667]


In [39]:
# std() - 표준편차
print(np.std(arr))

1.343709624716425


In [42]:
# cumsum() - 누적편차
print(np.cumsum(arr))
print(arr.cumsum())
print(arr.cumsum(axis=1))

[ 1  3  6  6  7 11]
[ 1  3  6  6  7 11]
[[1 3 6]
 [0 1 5]]


In [43]:
# median()  - 중앙값
print(np.median(arr))

1.5
