In [1]:
import numpy as np

### Section 6. N차원 배열의 병합

#### 6-1. 배열에 원소 추가 및 삭제

In [3]:
# python list
arr = [1,2,3,4,5,6,7,8]
arr.insert(2,50) # 삽입
print(arr)


# 1차원 배열
arr = np.arange(1,9)
arr = np.insert(arr,2,50)
print(arr)

[1, 2, 50, 3, 4, 5, 6, 7, 8]
[ 1  2 50  3  4  5  6  7  8]


In [6]:
# 2차원 배열
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr,2,50,axis=0)

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]


In [8]:
# delete()
arr = np.arange(1,13).reshape(3,4)
print(arr)

arr = np.delete(arr,2,axis=0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]


#### 6-2. 배열 간의 병합

In [12]:
# append()

arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)

print(arr1)
print(arr2, end="\n\n")

# axis = 0
arr3 = np.append(arr1,arr2, axis=0)
print(arr3, end="\n\n")

# axis = 1
arr3 = np.append(arr1,arr2, axis=1)
print(arr3, end="\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]



In [14]:
# vstack() hstack()

arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr3 = np.vstack((arr1,arr2))

print(arr3)

arr3 = np.stack((arr1,arr2))

print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
# concatenate()

arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr3 = np.concatenate([arr1,arr2], axis=1)

print(arr3)

arr4 = np.concatenate([arr1,arr2],axis=0)
print(arr4)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 6-3. N차원 배열의 병합

In [25]:
# 2차원 배열
arr = np.arange(1,13).reshape(3,4)
print(arr)

# vsplit() => axis = 0
arr_vsplit = np.vsplit(arr,3)
print(arr_vsplit)

# hsplit() => axis = 1
arr_hsplit = np.vsplit(arr,3)
print(arr_hsplit)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [26]:
# 3차원 배열
arr = np.random.randint(0,10,(4,6,8))
print(arr)

[[[4 0 3 6 3 9 6 3]
  [5 8 3 4 6 2 2 2]
  [9 8 1 7 4 5 4 3]
  [0 2 5 4 7 9 2 1]
  [4 0 8 4 9 6 7 5]
  [0 7 2 7 4 2 0 6]]

 [[5 2 2 4 7 1 5 9]
  [9 7 1 4 3 7 7 8]
  [8 4 4 2 5 2 7 8]
  [7 4 7 2 7 7 7 3]
  [3 0 5 5 6 2 3 4]
  [4 9 7 4 9 4 0 6]]

 [[6 0 7 6 6 6 5 1]
  [9 1 3 6 2 0 4 1]
  [6 3 6 5 6 3 1 6]
  [8 6 4 2 4 7 9 5]
  [1 2 6 7 6 0 6 4]
  [2 6 1 3 7 1 2 3]]

 [[3 3 1 6 4 7 2 5]
  [1 3 8 9 0 2 4 1]
  [8 3 5 3 4 8 2 2]
  [6 6 3 3 8 8 0 8]
  [4 1 2 7 8 3 6 8]
  [2 1 3 6 4 6 0 8]]]


In [27]:
arr_vsplit = np.vsplit(arr,2)
print(arr_vsplit)

[array([[[4, 0, 3, 6, 3, 9, 6, 3],
        [5, 8, 3, 4, 6, 2, 2, 2],
        [9, 8, 1, 7, 4, 5, 4, 3],
        [0, 2, 5, 4, 7, 9, 2, 1],
        [4, 0, 8, 4, 9, 6, 7, 5],
        [0, 7, 2, 7, 4, 2, 0, 6]],

       [[5, 2, 2, 4, 7, 1, 5, 9],
        [9, 7, 1, 4, 3, 7, 7, 8],
        [8, 4, 4, 2, 5, 2, 7, 8],
        [7, 4, 7, 2, 7, 7, 7, 3],
        [3, 0, 5, 5, 6, 2, 3, 4],
        [4, 9, 7, 4, 9, 4, 0, 6]]]), array([[[6, 0, 7, 6, 6, 6, 5, 1],
        [9, 1, 3, 6, 2, 0, 4, 1],
        [6, 3, 6, 5, 6, 3, 1, 6],
        [8, 6, 4, 2, 4, 7, 9, 5],
        [1, 2, 6, 7, 6, 0, 6, 4],
        [2, 6, 1, 3, 7, 1, 2, 3]],

       [[3, 3, 1, 6, 4, 7, 2, 5],
        [1, 3, 8, 9, 0, 2, 4, 1],
        [8, 3, 5, 3, 4, 8, 2, 2],
        [6, 6, 3, 3, 8, 8, 0, 8],
        [4, 1, 2, 7, 8, 3, 6, 8],
        [2, 1, 3, 6, 4, 6, 0, 8]]])]
