In [1]:
import numpy as np

### Section 4. N차원 배열 정렬

#### 4-1. 1차원 배열의 정렬

In [2]:
arr = np.random.randint(10,size=10)
print(arr)

[6 8 2 5 8 1 1 2 1 5]


In [7]:
# 오름차순
print(np.sort(arr))

# 내림차순

print(np.sort(arr)[::-1])

[1 1 1 2 2 5 5 6 8 8]
[8 8 6 5 5 2 2 1 1 1]


In [9]:
print(arr) # 원본 배열에는 해당이 안됌

# 정렬을 유지하려면
arr = np.sort(arr)
print(arr)
arr.sort()
print(arr)

[6 8 2 5 8 1 1 2 1 5]
[1 1 1 2 2 5 5 6 8 8]
[1 1 1 2 2 5 5 6 8 8]
