In [2]:
import numpy as np

#1차원 배열
arr = np.array([1,2,3])
print(arr)

#2차원 배열
arr = np.array([[1,2,3],[4,5,6]])
print(arr)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [4]:
print(arr.shape)
print(arr,arr.size)

(2, 3)
[[1 2 3]
 [4 5 6]] 6


In [6]:
arr = np.array([1,2,3,34,34,2],dtype=np.int32)
arr = np.array([1,2,3,34,4,4],dtype=np.int64)

In [10]:
arr = np.zeros([2,3])

print(arr)

arr = np.zeros([2,2,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [19]:
arr = np.ones([4,5])
print(arr)

arr = np.eye(3,4, k=1)
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
arr = np.full((2,3),5)
print(arr)

arr = np.full((3,4),1)
print(arr)

[[5 5 5]
 [5 5 5]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [23]:
arr = np.ones([3,4])
print(arr)

arr = np.ones_like(arr)

print(arr)


arr = np.ones([3,4])
print(arr, arr.dtype)
arr = np.ones_like(arr)
print(arr,arr.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [24]:
lst = list(range(0,9,2))
print(lst)

[0, 2, 4, 6, 8]


In [34]:
arr = np.arange(9)
print(arr)

arr = np.arange(3,12)
print(arr)

arr = np.arange(stop=9, step=2, start=0)
print(arr)


[0 1 2 3 4 5 6 7 8]
[ 3  4  5  6  7  8  9 10 11]
[0 2 4 6 8]


In [38]:
arr = np.linspace(0,20,100)
print(arr)

[ 0.          0.2020202   0.4040404   0.60606061  0.80808081  1.01010101
  1.21212121  1.41414141  1.61616162  1.81818182  2.02020202  2.22222222
  2.42424242  2.62626263  2.82828283  3.03030303  3.23232323  3.43434343
  3.63636364  3.83838384  4.04040404  4.24242424  4.44444444  4.64646465
  4.84848485  5.05050505  5.25252525  5.45454545  5.65656566  5.85858586
  6.06060606  6.26262626  6.46464646  6.66666667  6.86868687  7.07070707
  7.27272727  7.47474747  7.67676768  7.87878788  8.08080808  8.28282828
  8.48484848  8.68686869  8.88888889  9.09090909  9.29292929  9.49494949
  9.6969697   9.8989899  10.1010101  10.3030303  10.50505051 10.70707071
 10.90909091 11.11111111 11.31313131 11.51515152 11.71717172 11.91919192
 12.12121212 12.32323232 12.52525253 12.72727273 12.92929293 13.13131313
 13.33333333 13.53535354 13.73737374 13.93939394 14.14141414 14.34343434
 14.54545455 14.74747475 14.94949495 15.15151515 15.35353535 15.55555556
 15.75757576 15.95959596 16.16161616 16.36363636 16