In [2]:
import numpy as np

#1차원 배열
arr = np.array([1,2,3])
print(arr)

#2차원 배열
arr = np.array([[1,2,3],[4,5,6]])
print(arr)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [4]:
print(arr.shape)
print(arr,arr.size)

(2, 3)
[[1 2 3]
 [4 5 6]] 6


In [6]:
arr = np.array([1,2,3,34,34,2],dtype=np.int32)
arr = np.array([1,2,3,34,4,4],dtype=np.int64)

In [10]:
arr = np.zeros([2,3])

print(arr)

arr = np.zeros([2,2,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [19]:
arr = np.ones([4,5])
print(arr)

arr = np.eye(3,4, k=1)
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
arr = np.full((2,3),5)
print(arr)

arr = np.full((3,4),1)
print(arr)

[[5 5 5]
 [5 5 5]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [23]:
arr = np.ones([3,4])
print(arr)

arr = np.ones_like(arr)

print(arr)


arr = np.ones([3,4])
print(arr, arr.dtype)
arr = np.ones_like(arr)
print(arr,arr.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64
